# Generated by Django 4.2.2 on 2023-07-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='customer',
            new_name='company',
        ),
    ]
