# Generated by Django 4.2.2 on 2023-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0002_profile_organization'),
        ('taskmaster', '0002_rename_customer_task_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_representative',
            field=models.ManyToManyField(to='web_auth.profile'),
        ),
    ]
