# Generated by Django 4.2.2 on 2023-08-06 11:27

import django.core.validators
from django.db import migrations, models
import taskmaster_django_crm_project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0004_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), taskmaster_django_crm_project.validators.validate_first_capital, taskmaster_django_crm_project.validators.validate_all_alpha]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='annual_value',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='potential_annual_value',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
