# Generated by Django 4.2.2 on 2023-08-07 13:51

import django.core.validators
from django.db import migrations, models
import taskmaster_django_crm_project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0006_alter_contract_annual_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), taskmaster_django_crm_project.validators.validate_first_capital]),
        ),
    ]
